# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

general {
    col.active_border = rgb(85abbc)
    col.inactive_border = rgb(4a5a5d)
}


layerrule {
  name = layerrule-1
  blur = on
  ignore_alpha = 0
  match:namespace = walker
}

layerrule {
  name = layerrule-3
  blur = on
  ignore_alpha = 0.2
  match:namespace = mako
}


layerrule {
  name = layerrule-5
  blur = on
  match:namespace = swayosd
}
